services:
  - type: web
    name: acai-express-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: TZ
        value: America/Sao_Paulo
      - key: DATABASE_URL
        sync: false
      - key: OWNER_USUARIO
        sync: false
      - key: OWNER_SENHA
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        value: BFuan3U92UOwmTmJEFJT88aoARZTpjZ76PY4zK3p5lxYMJ65zK21A-Xd9fMuG7d_GH8q6m6OSi86zHyP8PWXEc4
      - key: VAPID_CONTATO
        value: mailto:kauesalazarcardoso123@gmail.com
